# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# ~/.config/starship.toml
#
# ### Variant 2: two line prompt, no background in top line, separators on left side
# *** Borrowed from a design seen in a zsh (should be from https://github.com/romkatv/powerlevel10k)
#
# - No filling solid line in top row: 
#   Replace '$fill\' with just one character '\' or just completely delete the line that contains '$fill\' further down,
#   within the format-block: format = """ ... """.
#
# - '$line_break': everything from the next line on refers to the second line of the prompt.
#
# - Some modules listed further down will not show up (all the time), as their default value is 'disabled = true' or
#   they are only displayed under certain conditions.
#
# - Symbols:
#   Don't be confused if you see this toml file via web browser on a website, gist, ... and you don't see any "real" symbols further down.
#   If Nerd-fonts are already installed on your system (e.g. MesloLG Nerd Font, FiraCode Nerd Font, ...) it should work.


# Customizing the prompt (and placing desired modules at desired position and sequence):
format = """
$os\
$username\
$hostname\
$sudo\
$directory\
$git_branch$git_commit$git_state$git_metrics$git_status\
$jobs\
$memory_usage\
[ ](fg:#242424)\
$cmd_duration\
$fill\
$line_break\
[$status\
$localip\
$character]($style)
"""

# Inserts a blank line between shell prompts:
add_newline = true

# Customization and activation of some modules:
# Listed in the order of their position in the module row above
[os]
format = "[ $symbol ]($style)[ ]()"
style = "fg:#AAAAAA"
disabled = false

[os.symbols]
Alpine = "ÔåÄ"
Amazon = "Ôâ∞"
Android = "Óúé"
Arch = "ÔåÉ"
CentOS = "ÔåÑ"
Debian = "ÔåÜ"
DragonFly = "üêâ" # "ÓûÜ"
Emscripten = "üîó"
EndeavourOS = "Ôå¢" # "Ôûª"
Fedora = "Ôåä"
FreeBSD = "Ôåå"
Garuda = "ÔÖº"
Gentoo = "Ôåç"
HardenedBSD = "Ô¶ó"
Illumos = "üê¶"
Linux = "ÔåÆ"
Macos = "ÔåÇ"
Manjaro = "Ôåí"
Mariner = "ÔÖº"
MidnightBSD = "üåò"
Mint = "Ôåé"
NetBSD = "ÔÖº"
NixOS = "Ôåì"
OpenBSD = "Ôå®" # "ÔÖº"
OpenCloudOS = "‚òÅÔ∏è"
openEuler = "ÔÖº"
openSUSE = "Ôåî"
OracleLinux = "‚äÇ‚äÉ"
Pop = "Ôå™" # "ÔÖº"
Raspbian = "Ôåï"
Redhat = "Ôåñ"
RedHatEnterprise = "Ôåñ"
Redox = "üß™"
Solus = "Ôå≠" # "ÔÖº "
SUSE = "Ôåî"
Void = "ÔåÆ"
Ubuntu = "Ôåõ"
Unknown = "ÔÑà"
Windows = "Óúè"

[username]
format = '[> ](fg:green italic)[$user]($style)[ ]()' # ÓÇ±
style_user = 'fg:green bold italic'
style_root = 'fg:red bold underline blink'
show_always = true
disabled = false

[hostname]
format = '[$ssh_symbol ](fg:green bold)[$hostname](fg:green bold)[ ]()'
ssh_only = true
ssh_symbol = 'ÓçÆ' # 'ÔÖΩ‚áí' # 'Ô£∑ ' # 'Ô¨Å‚áí'
#trim_at = '.companyname.com'
disabled = false

[sudo]
format = '[> ](fg:red bold)[as $symbol]($style)'
style = 'fg:red bold'
symbol = 'Ó©¨ ' # 'Ôîä ‚ùØ '
disabled = false

[directory]
format = '[> ](fg:cyan bold)[$read_only]($read_only_style)[$repo_root]($repo_root_style)[$path]($style)'
style = 'fg:cyan italic bold'
home_symbol = 'Ó¨Ü ~'
read_only = 'Ôëñ ' # 'Ô£≠ ' # 'Ô£Æ ''
read_only_style = 'fg:cyan'
truncation_length = 7
truncation_symbol = '‚Ä¶/'
truncate_to_repo = true
repo_root_format = '[> ](fg:cyan bold)[$read_only]($read_only_style)[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[ ]()'
repo_root_style	= 'fg:cyan bold'
use_os_path_sep = true
disabled = false

[git_branch]
format = '[‚ùØ $symbol $branch(:$remote_branch)]($style)[ ]()'
style = 'fg:#E04D27 italic'
symbol = 'Û∞ä¢'
#ignore_branches = ['master', 'main']

[git_commit]
format = '[\($hash$tag\)]($style)[ ]()'
style = 'fg:#E04D27 italic'
commit_hash_length = 8
tag_symbol = 'Ôêí ' # 'ÔÄ´ ''
disabled = false

[git_metrics]
format = '[\[+$added/]($added_style)[-$deleted\]]($deleted_style)[ ]()'
added_style = 'fg:#E04D27'
deleted_style = 'fg:#E04D27'
disabled = false

[git_status]
# place symbols before '$count'
format = '([$all_status$ahead_behind]($style))'
style = 'fg:#E04D27 italic'
conflicted = '[ÔëØ${count} ](fg:red)'
ahead = '[‚á°${count} ](fg:yellow)'
behind = '[‚á£${count} ](fg:yellow)'
diverged = '[‚áï${ahead_count}‚á°${behind_count}‚á£ ](fg:yellow)' # ‚áï ‚Üï ‚á≥ Û∞ππ Û∞π∫ Û∞ßà 
up_to_date = '[‚úì ](fg:green)'
untracked = '[Û∞üâ${count} ](fg:red)' # 'ÔÅ∞ ' # '? '
stashed = '[Óúá${count} ](fg:#A52A2A)' # 'üì¶ '# 'Óûõ ' # 'Ôíá ' # 'Óúê ' # 'Ó¨â ' 
modified = '[Û∞∑â${count} ](fg:#C8AC00)' # 'üìù' # '! ' # Óûè # ÔÇ≠ # ÔÉê
staged = '[ÔÉë${count} ](fg:green)' # '+ '
renamed = '[Û∞∏≤${count} ](fg:yellow)' # 'Ôóà ' # 'Ô´¶' # ·¥Ç # Ôù§ # ÔûÉ # ÔÉå # Ô≥≥
deleted = '[Û∞õå${count} ](fg:orange)' # 'üóë ' '- '
disabled = false

[jobs]
format = '[ > ](fg:blue bold)[$number$symbol]($style)'
style = 'fg:blue italic'
symbol = 'ÓÆ¢' # 'Ô™Ç' # 'Û∞úé' # 'ÓÆ¢' # '‚ú¶'
symbol_threshold = 1
number_threshold = 4
disabled = false

[memory_usage]
format = '[ > ](fg:purple bold)[$symbol ${ram} ${swap}]($style)'
style = 'fg:purple'
symbol = 'Û∞òö ' # '# 'Ô¨ô / Û∞æµ' # 'Û∞çõ Û∞æµ' # 'Ô¨ô Û∞æ¥' # 'Ô¨ô Û∞æ∂' # 'Ô¨ô Û∞æ∑' 'Ô¨ô Û∞£Ç'
threshold = 75
disabled = false

[cmd_duration]
format = '[< Û∞îõ $duration ]($style)'
style = 'fg:yellow italic'
min_time = 500
disabled = false

[fill]
style = 'fg:#505050'
symbol = '‚îÄ'

[status]
format = '[$symbol$status $hex_status Ó™¢ $signal_number-$signal_name ]($style)'
style = 'fg:red italic'
symbol = '‚úò '
disabled = false

[localip]
format = '[$localipv4 ](fg:green bold)'
ssh_only = true
disabled = false

[character]
success_symbol = '[](bold italic green)'
